# Generated by Django 5.1.7 on 2025-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('units', models.IntegerField()),
                ('paper_sequence', models.CharField(max_length=50)),
                ('pages_per_book', models.IntegerField()),
                ('printing_requirement', models.CharField(max_length=200)),
                ('gluing_method', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
